In [74]:
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd
import random 
import plotly.express as px
import plotly.io as pio
import nbformat
import polars as pl
import bottleneck as bn

In [19]:
df = pl.read_csv("trainns.csv")
df.head()

shape: (5, 12)
┌─────────────┬──────────┬────────┬───────────────────┬───┬───────────┬─────────┬───────┬──────────┐
│ PassengerId ┆ Survived ┆ Pclass ┆ Name              ┆ … ┆ Ticket    ┆ Fare    ┆ Cabin ┆ Embarked │
│ ---         ┆ ---      ┆ ---    ┆ ---               ┆   ┆ ---       ┆ ---     ┆ ---   ┆ ---      │
│ i64         ┆ i64      ┆ i64    ┆ str               ┆   ┆ str       ┆ f64     ┆ str   ┆ str      │
╞═════════════╪══════════╪════════╪═══════════════════╪═══╪═══════════╪═════════╪═══════╪══════════╡
│ 1           ┆ 0        ┆ 3      ┆ Braund, Mr. Owen  ┆ … ┆ A/5 21171 ┆ 7.25    ┆ null  ┆ S        │
│             ┆          ┆        ┆ Harris            ┆   ┆           ┆         ┆       ┆          │
│ 2           ┆ 1        ┆ 1      ┆ Cumings, Mrs.     ┆ … ┆ PC 17599  ┆ 71.2833 ┆ C85   ┆ C        │
│             ┆          ┆        ┆ John Bradley (Fl… ┆   ┆           ┆         ┆       ┆          │
│ 3           ┆ 1        ┆ 3      ┆ Heikkinen, Miss.  ┆ … ┆ STON/O2.  ┆ 7.925   ┆ null  ┆ S        │
│             ┆          ┆        ┆ Laina             ┆   ┆ 3101282   ┆         ┆       ┆          │
│ 4           ┆ 1        ┆ 1      ┆ Futrelle, Mrs.    ┆ … ┆ 113803    ┆ 53.1    ┆ C123  ┆ S        │
│             ┆          ┆        ┆ Jacques Heath (…  ┆   ┆           ┆         ┆       ┆          │
│ 5           ┆ 0        ┆ 3      ┆ Allen, Mr.        ┆ … ┆ 373450    ┆ 8.05    ┆ null  ┆ S        │
│             ┆          ┆        ┆ William Henry     ┆   ┆           ┆         ┆       ┆          │
└─────────────┴──────────┴────────┴───────────────────┴───┴───────────┴─────────┴───────┴──────────┘

Выведите основную информацию о датасете: информацию о типах данных, число пропусков, средние значения и т.д

In [20]:
df.describe()

shape: (9, 13)
┌────────────┬─────────────┬──────────┬──────────┬───┬───────────┬───────────┬───────┬──────────┐
│ statistic  ┆ PassengerId ┆ Survived ┆ Pclass   ┆ … ┆ Ticket    ┆ Fare      ┆ Cabin ┆ Embarked │
│ ---        ┆ ---         ┆ ---      ┆ ---      ┆   ┆ ---       ┆ ---       ┆ ---   ┆ ---      │
│ str        ┆ f64         ┆ f64      ┆ f64      ┆   ┆ str       ┆ f64       ┆ str   ┆ str      │
╞════════════╪═════════════╪══════════╪══════════╪═══╪═══════════╪═══════════╪═══════╪══════════╡
│ count      ┆ 891.0       ┆ 891.0    ┆ 891.0    ┆ … ┆ 891       ┆ 891.0     ┆ 204   ┆ 889      │
│ null_count ┆ 0.0         ┆ 0.0      ┆ 0.0      ┆ … ┆ 0         ┆ 0.0       ┆ 687   ┆ 2        │
│ mean       ┆ 446.0       ┆ 0.383838 ┆ 2.308642 ┆ … ┆ null      ┆ 32.204208 ┆ null  ┆ null     │
│ std        ┆ 257.353842  ┆ 0.486592 ┆ 0.836071 ┆ … ┆ null      ┆ 49.693429 ┆ null  ┆ null     │
│ min        ┆ 1.0         ┆ 0.0      ┆ 1.0      ┆ … ┆ 110152    ┆ 0.0       ┆ A10   ┆ C        │
│ 25%        ┆ 224.0       ┆ 0.0      ┆ 2.0      ┆ … ┆ null      ┆ 7.925     ┆ null  ┆ null     │
│ 50%        ┆ 446.0       ┆ 0.0      ┆ 3.0      ┆ … ┆ null      ┆ 14.4542   ┆ null  ┆ null     │
│ 75%        ┆ 669.0       ┆ 1.0      ┆ 3.0      ┆ … ┆ null      ┆ 31.0      ┆ null  ┆ null     │
│ max        ┆ 891.0       ┆ 1.0      ┆ 3.0      ┆ … ┆ WE/P 5735 ┆ 512.3292  ┆ T     ┆ S        │
└────────────┴─────────────┴──────────┴──────────┴───┴───────────┴───────────┴───────┴──────────┘

In [21]:
df.mean()

shape: (1, 12)
┌─────────────┬──────────┬──────────┬──────┬───┬────────┬───────────┬───────┬──────────┐
│ PassengerId ┆ Survived ┆ Pclass   ┆ Name ┆ … ┆ Ticket ┆ Fare      ┆ Cabin ┆ Embarked │
│ ---         ┆ ---      ┆ ---      ┆ ---  ┆   ┆ ---    ┆ ---       ┆ ---   ┆ ---      │
│ f64         ┆ f64      ┆ f64      ┆ str  ┆   ┆ str    ┆ f64       ┆ str   ┆ str      │
╞═════════════╪══════════╪══════════╪══════╪═══╪════════╪═══════════╪═══════╪══════════╡
│ 446.0       ┆ 0.383838 ┆ 2.308642 ┆ null ┆ … ┆ null   ┆ 32.204208 ┆ null  ┆ null     │
└─────────────┴──────────┴──────────┴──────┴───┴────────┴───────────┴───────┴──────────┘

In [54]:
df.dtypes

[Int64,
 Int64,
 Int64,
 String,
 String,
 Float64,
 Int64,
 Int64,
 String,
 Float64,
 String,
 String]

Посчитайте количество пассажиров каждого класса (Pclass)

In [36]:
df1 = df.get_column("Pclass").value_counts()
df1

shape: (3, 2)
┌────────┬───────┐
│ Pclass ┆ count │
│ ---    ┆ ---   │
│ i64    ┆ u32   │
╞════════╪═══════╡
│ 1      ┆ 216   │
│ 3      ┆ 491   │
│ 2      ┆ 184   │
└────────┴───────┘

Выведите количество выживших мужчин и женщин на корабле

In [48]:
df2 = df.group_by(["Survived", "Sex"]).agg(pl.len())
df2

shape: (4, 3)
┌──────────┬────────┬─────┐
│ Survived ┆ Sex    ┆ len │
│ ---      ┆ ---    ┆ --- │
│ i64      ┆ str    ┆ u32 │
╞══════════╪════════╪═════╡
│ 0        ┆ male   ┆ 468 │
│ 1        ┆ female ┆ 233 │
│ 0        ┆ female ┆ 81  │
│ 1        ┆ male   ┆ 109 │
└──────────┴────────┴─────┘

Выведите часть таблицы с пассажирами, возраст которых больше 44 лет

In [67]:
df_s = df.sample(20, seed = 1)

In [70]:
df_s.filter(pl.col('Age') > 44)

shape: (1, 12)
┌─────────────┬──────────┬────────┬──────────────────────┬───┬───────────┬──────┬───────┬──────────┐
│ PassengerId ┆ Survived ┆ Pclass ┆ Name                 ┆ … ┆ Ticket    ┆ Fare ┆ Cabin ┆ Embarked │
│ ---         ┆ ---      ┆ ---    ┆ ---                  ┆   ┆ ---       ┆ ---  ┆ ---   ┆ ---      │
│ i64         ┆ i64      ┆ i64    ┆ str                  ┆   ┆ str       ┆ f64  ┆ str   ┆ str      │
╞═════════════╪══════════╪════════╪══════════════════════╪═══╪═══════════╪══════╪═══════╪══════════╡
│ 746         ┆ 0        ┆ 1      ┆ Crosby, Capt. Edward ┆ … ┆ WE/P 5735 ┆ 71.0 ┆ B22   ┆ S        │
│             ┆          ┆        ┆ Gifford              ┆   ┆           ┆      ┆       ┆          │
└─────────────┴──────────┴────────┴──────────────────────┴───┴───────────┴──────┴───────┴──────────┘

In [86]:
dfp = pd.read_csv('trainns.csv')

Посчитайте средний возраст пассажиров и его стандартное отклонение с помощью bottleneck - 1 бал

In [78]:
bn.nanmean(dfp['Age'])

29.69911764705882

In [79]:
bn.nanstd(dfp['Age'])

14.516321150817317

Для каждого пассажира умножьте значение столбца Fare на 1.3 и сохраните результаты как новый столбец Fare_new

In [ ]:
#res = [row.Fare * 1.3 for _, row in dfp.iterrows()]

In [ ]:
#def calc_fare(row):
  #return row.Fare * 1,3

In [ ]:
#dfp.apply(calc_fare, axis=1)

0         (7.25, 3)
1      (71.2833, 3)
2        (7.925, 3)
3         (53.1, 3)
4         (8.05, 3)
           ...
886       (13.0, 3)
887       (30.0, 3)
888      (23.45, 3)
889       (30.0, 3)
890       (7.75, 3)
Length: 891, dtype: object

In [90]:
dfp['Fare_new'] = dfp.apply(lambda row: row.Fare * 1.3, axis=1)
dfp.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_new
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,9.42500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,92.66829
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,10.30250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,69.03000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,10.46500

In [146]:
df3 = pd.read_csv('Housing.csv')
df3.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

Для каждого столбца определите оптимальный с точки зрения потребления памяти тип данных - напишите свои выводы в комментариях

In [147]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [148]:
df3.describe()

,price,area,bedrooms,bathrooms,stories,parking
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000

Для оптимального потребления памяти можно:
- уменьшить разрядность для числовых столбцов:
    - это подойдет для всех столбцов, кроме price, так как в нем хранятся слишком большие значения 
    - поэтому я заменю потребление памяти с int(64) до int(16)
- совершить переход к категориальным значениям для строковых значений
    - в данном случае в каждом строковом столбце содержатся данные которые можно переписать как категориальные

Поменяйте типы данных столбцов датафрейма на выбранные вами в прошлом пункте и сравните потребление памяти до и после оптимизации

Оптимизация числовых значений

In [149]:
df3 = df3.fillna(0)
df3['area'] = df3['area'].astype(np.int16)
df3['bathrooms'] = df3['bathrooms'].astype(np.int16)
df3['bedrooms'] = df3['bedrooms'].astype(np.int16)
df3['stories'] = df3['stories'].astype(np.int16)
df3['parking'] = df3['parking'].astype(np.int16)

In [150]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int16
 2   bedrooms          545 non-null    int16
 3   bathrooms         545 non-null    int16
 4   stories           545 non-null    int16
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int16
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int16(5), int64(1), object(7)
memory usage: 39.5+ KB

In [151]:
df3.describe()

,price,area,bedrooms,bathrooms,stories,parking
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000

Оптимизация строковых значений

In [152]:
df3.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [153]:
df3['mainroad'].info(memory_usage="deep")

<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: mainroad
Non-Null Count  Dtype
--------------  -----
545 non-null    object
dtypes: object(1)
memory usage: 27.7 KB

In [154]:
df3['mainroad'] = df3['mainroad'].astype("category")
df3['mainroad'].info(memory_usage="deep")

<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: mainroad
Non-Null Count  Dtype
--------------  -----
545 non-null    category
dtypes: category(1)
memory usage: 888.0 bytes

In [155]:
df3['guestroom'].info(memory_usage="deep")

<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: guestroom
Non-Null Count  Dtype
--------------  -----
545 non-null    object
dtypes: object(1)
memory usage: 27.4 KB

In [156]:
df3['guestroom'] = df3['guestroom'].astype("category")
df3['guestroom'].info(memory_usage="deep")

<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: guestroom
Non-Null Count  Dtype
--------------  -----
545 non-null    category
dtypes: category(1)
memory usage: 888.0 bytes

In [ ]:
df3['basement'] = df3['basement'].astype("category")
df3['basement'].info(memory_usage="deep")

<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: basement
Non-Null Count  Dtype
--------------  -----
545 non-null    category
dtypes: category(1)
memory usage: 888.0 bytes

In [158]:
df3['hotwaterheating'].info(memory_usage="deep")

<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: hotwaterheating
Non-Null Count  Dtype
--------------  -----
545 non-null    object
dtypes: object(1)
memory usage: 27.3 KB

In [159]:
df3['hotwaterheating'] = df3['hotwaterheating'].astype("category")
df3['hotwaterheating'].info(memory_usage="deep")

<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: hotwaterheating
Non-Null Count  Dtype
--------------  -----
545 non-null    category
dtypes: category(1)
memory usage: 888.0 bytes

In [160]:
df3['airconditioning'].info(memory_usage="deep")

<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: airconditioning
Non-Null Count  Dtype
--------------  -----
545 non-null    object
dtypes: object(1)
memory usage: 27.4 KB

In [161]:
df3['airconditioning'] = df3['airconditioning'].astype("category")
df3['airconditioning'].info(memory_usage="deep")

<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: airconditioning
Non-Null Count  Dtype
--------------  -----
545 non-null    category
dtypes: category(1)
memory usage: 888.0 bytes

In [162]:
df3['prefarea'].info(memory_usage="deep")

<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: prefarea
Non-Null Count  Dtype
--------------  -----
545 non-null    object
dtypes: object(1)
memory usage: 27.4 KB

In [163]:
df3['prefarea'] = df3['prefarea'].astype("category")
df3['prefarea'].info(memory_usage="deep")

<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: prefarea
Non-Null Count  Dtype
--------------  -----
545 non-null    category
dtypes: category(1)
memory usage: 888.0 bytes

In [164]:
df3['furnishingstatus'].info(memory_usage="deep")

<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: furnishingstatus
Non-Null Count  Dtype
--------------  -----
545 non-null    object
dtypes: object(1)
memory usage: 32.5 KB

In [165]:
df3['furnishingstatus'] = df3['furnishingstatus'].astype("category")
df3['furnishingstatus'].info(memory_usage="deep")

<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: furnishingstatus
Non-Null Count  Dtype
--------------  -----
545 non-null    category
dtypes: category(1)
memory usage: 966.0 bytes

In [167]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int16
 2   bedrooms          545 non-null    int16
 3   bathrooms         545 non-null    int16
 4   stories           545 non-null    int16
 5   mainroad          545 non-null    category
 6   guestroom         545 non-null    category
 7   basement          545 non-null    category
 8   hotwaterheating   545 non-null    category
 9   airconditioning   545 non-null    category
 10  parking           545 non-null    int16
 11  prefarea          545 non-null    category
 12  furnishingstatus  545 non-null    category
dtypes: category(7), int16(5), int64(1)
memory usage: 14.3 KB

Итого, вышло оптимизировать память c 55.5 KB до 14.3 KB